/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#630ed4",
        "primary-container": "#7c3aed",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary": "#ffffff",
        "on-primary-container": "#ede0ff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary": "#4b41e1",
        "secondary-container": "#645efb",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "tertiary": "#704500",
        "tertiary-container": "#905b00",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffe1c0",
        "background": "#f8f9fb",
        "surface": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "surface-variant": "#e1e2e4",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-surface-variant": "#4a4455",
        "outline": "#7b7487",
        "outline-variant": "#ccc3d8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'violet-glow': '0 4px 24px rgba(124, 58, 237, 0.25)',
        'sidebar-glow': '4px 0 24px rgba(124, 58, 237, 0.05)',
        'bento-hover': '0 4px 20px rgba(124, 58, 237, 0.08)',
        'modal-elevated': '0 20px 40px -15px rgba(0, 0, 0, 0.15)',
      },
      borderRadius: {
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
