import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Conversation, Message } from '../../types';
import { useAuth } from '../../context/AuthContext';
import { useTheme } from '../../context/ThemeContext';
import { api } from '../../lib/api';
import { generateAndDownloadChatPdf } from '../../lib/pdfExport';
import {
  Plus,
  MessageSquare,
  History,
  Shield,
  Layers,
  LogOut,
  Trash2,
  Sparkles,
  Download,
  Printer,
  FileText,
  ChevronDown,
  Moon,
  Sun,
  FileDown
} from 'lucide-react';

interface ChatSidebarProps {
  conversations: Conversation[];
  activeConvId: string | null;
  messages?: Message[];
  onSelectConversation: (id: string) => void;
  onNewChat: () => void;
  onDeleteConversation: (id: string) => void;
  onAskQuestion?: (question: string) => void;
}

export const ChatSidebar: React.FC<ChatSidebarProps> = ({
  conversations,
  activeConvId,
  messages = [],
  onSelectConversation,
  onNewChat,
  onDeleteConversation,
  onAskQuestion,
}) => {
  const { user, isAdmin, logout } = useAuth();
  const { isDark, toggleTheme } = useTheme();
  const location = useLocation();
  const [historySearchTerm, setHistorySearchTerm] = useState('');
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);

  const filtered = conversations.filter((c) =>
    c.title.toLowerCase().includes(historySearchTerm.toLowerCase())
  );

  const groupConversations = () => {
    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const yesterday = today - 86400000;
    const weekAgo = today - 7 * 86400000;

    const groups: { [key: string]: Conversation[] } = {
      Today: [],
      Yesterday: [],
      'Previous 7 Days': [],
      Older: [],
    };

    filtered.forEach((c) => {
      const cDate = new Date(c.updated_at || c.created_at).getTime();
      if (cDate >= today) {
        groups.Today.push(c);
      } else if (cDate >= yesterday) {
        groups.Yesterday.push(c);
      } else if (cDate >= weekAgo) {
        groups['Previous 7 Days'].push(c);
      } else {
        groups.Older.push(c);
      }
    });

    return groups;
  };

  const grouped = groupConversations();

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (window.confirm('Delete this conversation?')) {
      setDeletingId(id);
      try {
        await api.conversations.delete(id);
        onDeleteConversation(id);
      } catch (err) {
        console.error('Failed to delete conversation', err);
      } finally {
        setDeletingId(null);
      }
    }
  };

  // Export chat transcript as Markdown (.md)
  const exportMarkdown = () => {
    if (messages.length === 0) {
      alert('No messages in the current conversation to export.');
      return;
    }

    const activeConv = conversations.find((c) => c.id === activeConvId);
    const title = activeConv?.title || 'College AI Inquiry Session';
    const timestamp = new Date().toLocaleString();

    let md = `# ${title}\n`;
    md += `*Generated by VibrantAI College Knowledge Assistant on ${timestamp}*\n\n---\n\n`;

    messages.forEach((msg) => {
      if (msg.role === 'user') {
        md += `### 👤 Student Question:\n${msg.content}\n\n`;
      } else {
        md += `### 🎓 VibrantAI Grounded Answer:\n${msg.content}\n\n`;
        if (msg.confidence) {
          md += `*Relevance Confidence: ${Math.round(msg.confidence * 100)}%*\n\n`;
        }
      }
      md += `---\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `college_chat_${activeConvId || 'session'}.md`;
    link.click();
    URL.revokeObjectURL(url);
    setIsExportMenuOpen(false);
  };

  // Automatically Generate and Download PDF File (No hyperlinks)
  const exportPdf = () => {
    if (messages.length === 0) {
      alert('No messages to export.');
      return;
    }
    const currentConv = conversations.find((c) => c.id === activeConvId);
    const title = currentConv?.title || (messages[0]?.content ? messages[0].content.slice(0, 40) : 'College Chat Transcript');
    generateAndDownloadChatPdf(messages, title, isDark ? 'dark' : 'light');
    setIsExportMenuOpen(false);
  };

  return (
    <aside className="w-64 lg:w-72 border-r border-surface-variant dark:border-gray-800 bg-surface dark:bg-[#111827] shadow-sidebar-glow flex flex-col h-screen select-none z-30 flex-shrink-0 transition-colors">
      {/* Brand Header */}
      <div className="p-5 pb-3">
        <Link to="/chat" className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-full bg-[#4B41E1] flex items-center justify-center text-white shadow-xs">
            <Sparkles className="w-4 h-4 fill-white text-white" />
          </div>
          <div>
            <h1 className="text-xl font-extrabold tracking-tight" style={{ color: '#4B41E1' }}>
              VibrantAI
            </h1>
            <p className="text-[11px] font-bold text-gray-500 dark:text-gray-400 -mt-0.5">
              College Knowledge Base
            </p>
          </div>
        </Link>
      </div>

      {/* New Chat Primary Button */}
      <div className="px-3.5 mb-2">
        <button
          onClick={onNewChat}
          className="w-full flex items-center justify-center gap-2 bg-[#4B41E1] text-white py-2.5 rounded-xl font-bold text-sm shadow-sm hover:bg-[#3b32c4] transition-all active:scale-95 duration-150 cursor-pointer"
        >
          <Plus className="w-4 h-4" />
          <span>New Chat</span>
        </button>
      </div>

      {/* Main Navigation Menu */}
      <div className="px-3 mb-2">
        <ul className="flex flex-col gap-1 text-xs">
          <li>
            <Link
              to="/chat"
              className={`flex items-center gap-2.5 px-3 py-2 rounded-xl transition-colors font-medium ${location.pathname.startsWith('/chat')
                  ? 'text-[#4B41E1] font-bold bg-[#4B41E1]/10 dark:bg-[#4B41E1]/20 border-r-3 border-[#4B41E1]'
                  : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'
                }`}
            >
              <MessageSquare className="w-4 h-4 text-[#4B41E1]" />
              <span>Active Chat</span>
            </Link>
          </li>

          {isAdmin && (
            <>
              <li>
                <Link
                  to="/admin"
                  className={`flex items-center gap-2.5 px-3 py-2 rounded-xl transition-colors font-medium ${location.pathname === '/admin'
                      ? 'text-[#4B41E1] font-bold bg-[#4B41E1]/10 dark:bg-[#4B41E1]/20 border-r-3 border-[#4B41E1]'
                      : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'
                    }`}
                >
                  <Shield className="w-4 h-4 text-[#4B41E1]" />
                  <span>Admin Analytics</span>
                </Link>
              </li>
              <li>
                <Link
                  to="/admin/documents"
                  className={`flex items-center gap-2.5 px-3 py-2 rounded-xl transition-colors font-medium ${location.pathname.startsWith('/admin/documents')
                      ? 'text-[#4B41E1] font-bold bg-[#4B41E1]/10 dark:bg-[#4B41E1]/20 border-r-3 border-[#4B41E1]'
                      : 'text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800'
                    }`}
                >
                  <Layers className="w-4 h-4 text-[#4B41E1]" />
                  <span>Document Vault</span>
                </Link>
              </li>
            </>
          )}
        </ul>
      </div>

      {/* Export Chat Dropdown */}
      {messages.length > 0 && (
        <div className="px-3.5 mb-2 relative">
          <button
            onClick={() => setIsExportMenuOpen(!isExportMenuOpen)}
            className="w-full flex items-center justify-between px-3 py-1.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/80 hover:bg-gray-100 text-xs font-semibold text-gray-700 dark:text-gray-300 transition-colors cursor-pointer"
          >
            <div className="flex items-center gap-1.5">
              <Download className="w-3.5 h-3.5 text-[#4B41E1]" />
              <span>Export Chat</span>
            </div>
            <ChevronDown className="w-3.5 h-3.5" />
          </button>

          {isExportMenuOpen && (
            <div className="absolute left-3.5 right-3.5 top-9 bg-white dark:bg-[#111827] border border-gray-200 dark:border-gray-700 rounded-xl shadow-xl p-1 z-40 animate-in zoom-in-95 space-y-1">

              <button
                onClick={exportPdf}
                className="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg text-xs font-medium text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 text-left cursor-pointer"
              >
                <FileDown className="w-3.5 h-3.5 text-[#4B41E1]" />
                <span>Download PDF Document (.pdf)</span>
              </button>
            </div>
          )}
        </div>
      )}

      <div className="px-3.5 my-1">
        <div className="h-px bg-gray-200 dark:bg-gray-800" />
      </div>

      {/* Chat History Section */}
      <div className="flex-1 overflow-y-auto px-3 py-2 space-y-4 custom-scrollbar">
        <div className="flex items-center justify-between px-1">
          <span className="text-[10px] font-bold uppercase tracking-wider text-gray-400 dark:text-gray-500">
            Recent Conversations
          </span>
          <span className="text-[10px] font-mono text-gray-400">
            {conversations.length}
          </span>
        </div>

        {Object.entries(grouped).map(([label, convs]) => {
          if (convs.length === 0) return null;
          return (
            <div key={label} className="space-y-1">
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2.5 block">
                {label}
              </span>
              <div className="space-y-0.5">
                {convs.map((c) => {
                  const isActive = c.id === activeConvId;
                  const isDeleting = c.id === deletingId;
                  return (
                    <div
                      key={c.id}
                      onClick={() => onSelectConversation(c.id)}
                      className={`group flex items-center justify-between px-3 py-2 rounded-xl text-xs cursor-pointer transition-all ${isActive
                          ? 'bg-gray-100 dark:bg-gray-800 font-semibold text-[#4B41E1] shadow-2xs'
                          : 'text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800/60'
                        }`}
                    >
                      <div className="flex items-center gap-2 truncate min-w-0 pr-2">
                        <History className="w-3.5 h-3.5 text-gray-400 flex-shrink-0" />
                        <span className="truncate">{c.title || 'Untitled Conversation'}</span>
                      </div>

                      <button
                        onClick={(e) => handleDelete(e, c.id)}
                        disabled={isDeleting}
                        className="opacity-0 group-hover:opacity-100 p-1 rounded-md text-gray-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-900/30 transition-all flex-shrink-0 cursor-pointer"
                        title="Delete chat"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}

        {conversations.length === 0 && (
          <div className="py-6 text-center text-xs text-gray-400">
            <span>No conversation history yet.</span>
          </div>
        )}
      </div>

      {/* Footer Profile */}
      <div className="p-3 border-t border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-[#0B0F17]">
        <div className="flex items-center justify-between">
          <Link
            to="/profile"
            className="flex items-center gap-2.5 p-1 rounded-xl hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors min-w-0 pr-2"
          >
            <div className="w-8 h-8 rounded-full bg-[#4B41E1] text-white flex items-center justify-center font-bold text-xs shadow-xs flex-shrink-0">
              {user?.full_name ? user.full_name.charAt(0).toUpperCase() : 'U'}
            </div>
            <div className="truncate min-w-0">
              <span className="font-bold text-xs text-gray-800 dark:text-gray-200 block truncate">
                {user?.full_name || user?.email || 'User'}
              </span>
              <span className="text-[10px] text-gray-400 font-mono uppercase block">
                {user?.role || 'Student'}
              </span>
            </div>
          </Link>

          <div className="flex items-center gap-1 flex-shrink-0">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-lg text-gray-500 dark:text-gray-400 hover:text-[#4B41E1] hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer"
              title={isDark ? 'Switch to Light Theme' : 'Switch to Dark Theme'}
            >
              {isDark ? <Sun className="w-4 h-4 text-amber-400" /> : <Moon className="w-4 h-4" />}
            </button>

            <button
              onClick={logout}
              className="p-2 rounded-lg text-gray-500 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-900/30 transition-colors cursor-pointer"
              title="Sign Out"
            >
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </aside>
  );
};
